namespace RuinaoSoftwareWpf;

/// <summary>
/// 多语言服务的具体实现。
///
/// 目前只支持“中文 / 英文”切换。所有界面文字都通过一个 key 从这个字典里取，
/// 这样切换语言时，只要改 IsChinese，再通知界面刷新即可。
///
/// 可以理解为：它是软件的“翻译字典”。
/// </summary>
public sealed class AppLocalizationService : ILocalizationService
{
    // 字典 key -> (中文, 英文)
    // 新增界面文字时，只需要在这里加一项，然后在 LocalizationViewModel 里暴露属性即可。
    private readonly Dictionary<string, (string Zh, string En)> texts = new()
    {
        ["Language"] = ("中文", "EN"),
        ["Dashboard"] = ("总览", "Dashboard"),
        ["PageControl"] = ("模式：电刺激", "Electrical Stimulation"),
        ["ClosedLoopControl"] = ("闭环控制", "Closed-loop Control"),
        ["AssessmentCapture"] = ("数字表型采集", "Digital Phenotyping"),
        ["EegSignalCapture"] = ("脑电信号采集", "EEG Signal Acquisition"),
        ["ElectrodePlanning"] = ("智能电极规划", "Electrode Planning"),
        ["HeadModel"] = ("头模型构建", "Head Model"),
        ["FemSimulation"] = ("有限元仿真", "FEM Simulation"),
        ["ProtocolManager"] = ("处方", "Prescription"),
        ["TreatmentHistory"] = ("记录", "Records"),
        ["TreatmentHistoryTitle"] = ("治疗历史记录", "Treatment History"),
        ["Settings"] = ("设置", "Settings"),
        ["Help"] = ("帮助", "Help"),
        ["PrescriptionMenu"] = ("处方", "Protocol"),
        ["DeviceMenu"] = ("设备", "Device"),
        ["SimulationMenu"] = ("仿真", "Simulation"),
        ["ToolsMenu"] = ("工具", "Tools"),
        ["AccountMenu"] = ("账号", "Account"),
        ["Connect"] = ("联机", "Connect"),
        ["Disconnect"] = ("断开", "Disconnect"),
        ["Handshake"] = ("握手检测", "Handshake"),
        ["ReadProductModel"] = ("读取产品型号", "Read Product Model"),
        ["ReadBoardModel"] = ("读取板卡型号", "Read Board Model"),
        ["ImpedanceCheck"] = ("阻抗检测", "Impedance Check"),
        ["SwitchLanguage"] = ("切换为英文", "Switch to Chinese"),
        ["NewPrescription"] = ("新建处方", "New Protocol"),
        ["ImportPrescription"] = ("导入处方", "Import Protocol"),
        ["PrescriptionList"] = ("处方列表", "Protocol List"),
        ["LoadModel"] = ("加载模型", "Load Model"),
        ["RunSimulation"] = ("开始仿真", "Run Simulation"),
        ["SimulationResult"] = ("查看结果", "View Results"),
        ["OpenLogFolder"] = ("打开日志目录", "Open Log Folder"),
        ["ExportConfig"] = ("导出配置", "Export Config"),
        ["UserGuide"] = ("使用说明", "User Guide"),
        ["ShortcutHelp"] = ("快捷键说明", "Shortcuts"),
        ["About"] = ("关于软件", "About"),
        ["CurrentUser"] = ("当前用户", "Current User"),
        ["PermissionSettings"] = ("权限设置", "Permissions"),
        ["Logout"] = ("退出登录", "Log Out"),
        ["SystemInfo"] = ("系统信息", "System Info"),
        ["PlaceholderFeature"] = ("预留功能", "Reserved Feature"),
        ["ExitApplication"] = ("退出软件", "Exit"),
        ["StartButton"] = ("开始", "Start"),
        ["SynchronizedStartButton"] = ("同步开始", "Start Together"),
        ["EmergencyStopButton"] = ("紧急停止", "Emergency Stop"),
        ["Name"] = ("姓名", "Name"),
        ["Sex"] = ("性别", "Sex"),
        ["Age"] = ("年龄", "Age"),
        ["Navigation"] = ("导航", "Navigation"),
        ["Control"] = ("电刺激", "Electrical Stimulation"),
        ["StimulationTypeTitle"] = ("选择电刺激类型", "Choose Stimulation Type"),
        ["StimulationTypeHint"] = ("请选择本次治疗使用的电刺激模式", "Choose the stimulation mode for this treatment"),
        ["TemporalInterference"] = ("时间相干电刺激", "Temporal Interference Stimulation"),
        ["TranscranialDirectCurrent"] = ("经颅直流电刺激", "Transcranial Direct Current Stimulation"),
        ["ComingSoon"] = ("待开发", "Coming Soon"),
        ["Back"] = ("返回", "Back"),
        ["ModeTitle"] = ("模式：TI", "Mode: TI"),
        ["DirectCurrentModeTitle"] = ("模式：tDCS", "Mode: tDCS"),
        ["ChannelHint"] = ("选择一个 TI 组后，右侧只显示该组对应的一对通道信息", "Select one TI group; only its channel pair is shown on the right"),
        ["RemainingTime"] = ("剩余时间", "Remaining"),
        ["StatusMonitor"] = ("状态监控", "Status"),
        ["AnodeTemp"] = ("阳极 °C", "Anode °C"),
        ["CathodeTemp"] = ("阴极 °C", "Cathode °C"),
        ["Impedance"] = ("阻抗 Ω", "Impedance Ω"),
        ["Amplitude"] = ("幅值", "Amplitude"),
        ["RampUp"] = ("渐升", "Ramp Up"),
        ["RampDown"] = ("渐降", "Ramp Down"),
        ["Polarity"] = ("极性", "Polarity"),
        ["Mode"] = ("模式", "Mode"),
        ["IntervalMode"] = ("间隔", "Interval"),
        ["ContinuousMode"] = ("连续", "Continuous"),
        ["Duration"] = ("刺激时间", "Duration"),
        ["IntervalTime"] = ("间隔时间", "Interval Time"),
        ["SingleDuration"] = ("单次时长", "Single Duration"),
        ["CarrierFrequency"] = ("载波频率", "Carrier Freq."),
        ["Waveform"] = ("波形展示", "Waveform"),
        ["Electrode"] = ("电极：", "Electrode: "),
        ["FemStep1"] = ("步骤 1", "Step 1"),
        ["FemStep2"] = ("步骤 2", "Step 2"),
        ["FemLoadModel"] = ("加载模型", "Load Model"),
        ["FemVisualization"] = ("可视化", "Visualization"),
        ["FemLoadHeadModel"] = ("从 MRI 加载头部模型 (NIfTI/STL)", "Load Head Model from MRI (NIfTI/STL)"),
        ["FemChooseFile"] = ("选择文件", "Choose File"),
        ["FemCoronalSlice"] = ("冠状位切片", "Coronal Slice"),
        ["FemSagittalSlice"] = ("矢状位切片", "Sagittal Slice"),
        ["FemAxialSlice"] = ("轴位切片", "Axial Slice"),
        ["FemGenerateMontage"] = ("生成蒙太奇模型", "Generate Montage Model"),
        ["FemModelStatus"] = ("模型：未加载", "Model: not loaded"),
        ["FemSimulationStatus"] = ("仿真：空闲", "Simulation: idle"),
        ["DeviceOnline"] = ("仪器已联机", "Instrument online"),
        ["DeviceOffline"] = ("仪器未联机", "Instrument offline"),
        ["PlaceholderElectrodePlanning"] = ("该模块已预留导航入口，后续可接入电极布局算法、候选方案管理和自动规划结果。", "This module is reserved for electrode layout algorithms, candidate montage management, and planning results."),
        ["PlaceholderHeadModel"] = ("该模块已预留导航入口，后续可接入头模型构建、MRI/STL 导入和模型质量检查。", "This module is reserved for head model building, MRI/STL import, and model quality checks."),
        ["PlaceholderClosedLoopControl"] = ("该模块已预留导航入口，后续可接入闭环控制策略、实时反馈和自动干预流程。", "This module is reserved for closed-loop control strategies, real-time feedback, and automated intervention workflows."),
        ["PlaceholderEegSignalCapture"] = ("该模块已预留导航入口，后续可接入 EEG 设备联机、脑电数据采集、毫秒级时间戳标记和采集质量监控。", "This module is reserved for EEG device connection, EEG data acquisition, millisecond timestamp markers, and acquisition quality monitoring."),
        ["PlaceholderProtocolManager"] = ("该模块已预留导航入口，后续可接入处方 JSON 管理、模板复用和参数版本记录。", "This module is reserved for protocol JSON management, template reuse, and parameter version history."),
        ["PlaceholderTreatmentHistory"] = ("该模块已预留导航入口，后续可接入治疗记录、设备日志索引和报告追踪。", "This module is reserved for treatment records, device log indexes, and report tracking."),
        ["PlaceholderHelp"] = ("该模块已预留导航入口，后续可接入用户手册、快捷键说明和软件版本信息。", "This module is reserved for user guides, shortcuts, and software version information."),
        ["PlaceholderDefault"] = ("该页面框架已接入，具体业务功能将在后续模块中补充。", "The page shell is available; detailed business features can be added in later modules."),

        // ---------- 采集工作台 ----------
        ["CaptureWorkspaceModuleBadge"] = ("模块：{0}", "Module: {0}"),
        ["CaptureWorkspaceProcessTitle"] = ("执行流程", "Workflow"),
        ["CaptureWorkspaceCurrentStep"] = ("当前步骤：{0}", "Current step: {0}"),
        ["CaptureWorkspaceSharedDisplayTitle"] = ("{0}共享显示区", "{0} shared display area"),
        ["CaptureWorkspaceEnterFaceCheck"] = ("进入面部取景", "Enter face framing"),
        ["CaptureWorkspaceCameraPanelTitle"] = ("摄像头与人脸状态", "Camera and face status"),
        ["CaptureWorkspaceRefresh"] = ("刷新", "Refresh"),
        ["CaptureWorkspaceCameraPreview"] = ("摄像头实时预览", "Live camera preview"),
        ["CaptureWorkspaceModuleFlowTitle"] = ("模块流程", "Module flow"),
        ["CaptureWorkspaceDevelopmentClickable"] = ("开发可点", "Dev clickable"),
        ["CaptureWorkspaceNoCameraDetected"] = ("未检测到摄像头", "No camera detected"),
        ["CaptureWorkspaceNoCameraSelected"] = ("未选择摄像头", "No camera selected"),
        ["CaptureWorkspaceChooseCamera"] = ("请选择摄像头", "Please select a camera"),
        ["CaptureWorkspaceNoCameraAvailable"] = ("未检测到可用摄像头", "No available camera detected"),
        ["CaptureWorkspaceCameraSelected"] = ("已选择：{0}", "Selected: {0}"),
        ["CaptureWorkspaceOpeningCamera"] = ("正在打开摄像头...", "Opening camera..."),
        ["CaptureWorkspaceCameraOpenFailed"] = ("摄像头预览打开失败", "Camera preview failed to open"),
        ["CaptureWorkspaceNoFrameRead"] = ("未读取到画面", "No frame received"),
        ["CaptureWorkspaceNoFaceDetected"] = ("未检测到人脸", "No face detected"),
        ["CaptureWorkspaceFaceInsideFrame"] = ("人脸在取景框内", "Face is inside the frame"),
        ["CaptureWorkspaceMoveFaceIntoFrame"] = ("请将完整人脸移入虚线框", "Please move the full face into the dashed frame"),
        ["CaptureWorkspaceNoCameraStageNotice"] = ("当前未检测到可用摄像头，请连接笔记本摄像头或 USB 摄像头后点击右侧刷新。", "No available camera is detected. Connect the built-in or USB camera, then click Refresh on the right."),
        ["CaptureWorkspaceCameraNoFrameStageNotice"] = ("当前摄像头尚未显示实时画面，已尝试重新打开预览；如仍无画面，请检查设备占用或点击右侧刷新。", "The camera has not shown a live image yet. Preview has been reopened; if there is still no image, check device usage or click Refresh on the right."),
        ["CaptureWorkspaceFaceNotReadyStageNotice"] = ("当前未确认人脸在取景框内，请让用户正对摄像头，并将面部移动到右侧虚线范围内后再开始。", "The face is not confirmed inside the frame. Ask the user to face the camera and move the face into the dashed area before starting."),
        ["CaptureWorkspaceMediaStartFailed"] = ("音视频采集启动失败：{0}", "Audio/video capture failed to start: {0}"),
        ["CaptureWorkspaceMediaStartFailedNotice"] = ("音视频采集启动失败：{0}。请确认摄像头和麦克风未被其他程序占用。", "Audio/video capture failed to start: {0}. Make sure the camera and microphone are not occupied by another program."),
        ["CaptureWorkspaceSyncTestStartFailed"] = ("音画同步测试启动失败：{0}", "A/V sync test failed to start: {0}"),
        ["CaptureWorkspaceSyncTestStartFailedNotice"] = ("音画同步测试启动失败：{0}。请确认摄像头和麦克风未被其他程序占用。", "A/V sync test failed to start: {0}. Make sure the camera and microphone are not occupied by another program."),
        ["CaptureWorkspaceModuleMediaCompleted"] = ("{0}音视频采集完成", "{0} media capture completed"),
        ["CaptureWorkspaceRecordingInterruptedMessage"] = ("采集被中断，本次临时音视频未保存；请重新确认面部取景后开始当前模块。", "Capture was interrupted. Temporary media for this run was not saved. Confirm face framing again before restarting the current module."),
        ["CaptureWorkspaceLeaveCaptureWarning"] = ("当前正在执行“{0}”采集任务。\n\n切换到其他界面会暂停并中断当前采集，本次未完成的音视频不会保存。\n\n是否确认离开数字表型采集？", "The {0} capture task is currently running.\n\nSwitching to another page will pause and interrupt the current capture. Unfinished media will not be saved.\n\nLeave digital phenotyping?"),
        ["CaptureWorkspaceLeaveDemoWarning"] = ("当前正在播放“{0}”演示视频。\n\n切换到其他界面会停止本次演示，返回数字表型采集后需要从头重新观看演示视频。\n\n是否确认离开数字表型采集？", "The {0} demo video is currently playing.\n\nSwitching to another page will stop this demo. When returning to digital phenotyping, the demo must be watched from the beginning.\n\nLeave digital phenotyping?"),
        ["CaptureWorkspaceSyncTestRunning"] = ("正在录制音画同步测试，请做动作并同时发声作为锚点。\n剩余 {0} 秒后自动完成。", "Recording the A/V sync test. Make a visible action while speaking as an anchor.\nAutomatically completes in {0}s."),
        ["CaptureWorkspaceSyncTestReady"] = ("点击开始后录制约 60 秒，用于检查动作与声音是否同步。", "Click Start to record for about 60 seconds and check whether motion and sound are synchronized."),
        ["CaptureWorkspaceMainPrepare"] = ("当前准备阶段：检查摄像头、存储路径与患者信息", "Preparation: check camera, storage path, and patient information"),
        ["CaptureWorkspaceMainDemo"] = ("当前演示阶段：视频 / 图片将在此处大屏展示", "Demo stage: video or images will be shown here"),
        ["CaptureWorkspaceMainFaceCheck"] = ("当前面部取景阶段：必要时弹出人脸预览提醒", "Face framing: show face preview prompts when needed"),
        ["CaptureWorkspaceMainSyncTest"] = ("当前测试阶段：音画同步测试将在此处录制", "Test stage: A/V sync test will be recorded here"),
        ["CaptureWorkspaceMainBasicInfo"] = ("当前表单阶段：请完成个人基本信息填写", "Form stage: complete the basic information form"),
        ["CaptureWorkspaceMainVoiceBaseline"] = ("当前语音基线阶段：请按提示词持续发声", "Voice baseline: keep vocalizing according to the prompt"),
        ["CaptureWorkspaceMainWordReading"] = ("当前词语朗读阶段：请按中央词组顺序朗读", "Word reading: read the central word group in order"),
        ["CaptureWorkspaceMainShortTextReading"] = ("当前短文朗读阶段：请按中央短文内容朗读", "Passage reading: read the passage shown in the center"),
        ["CaptureWorkspaceMainEmotionQuestion"] = ("当前情绪问答阶段：请根据中央问题进行回答", "Emotion Q&A: answer the question shown in the center"),
        ["CaptureWorkspaceMainDotProbe"] = ("当前点探测阶段：请在星号出现后选择对应位置", "Dot probe: select the matching position after the asterisk appears"),
        ["CaptureWorkspaceMainPictureBrowse"] = ("当前图片浏览阶段：图片将在此处按顺序展示", "Picture browsing: images will be shown here in sequence"),
        ["CaptureWorkspaceMainVideoBrowse"] = ("当前视频浏览阶段：视频将在此处随机播放", "Video browsing: videos will be played here in random order"),
        ["CaptureWorkspaceMainEyeCalibration"] = ("当前校准阶段：此区域切换为眼动校准点阵", "Calibration stage: this area switches to the eye calibration point grid"),
        ["CaptureWorkspaceMainCompleted"] = ("当前完成阶段：准备进入{0}", "Completed: ready to enter {0}"),
        ["CaptureWorkspaceDevHintExecution"] = ("开发预览：此处后续显示 8 点 / 10 点校准内容", "Development preview: 8-point / 10-point calibration content is shown here"),
        ["CaptureWorkspaceDevHintDefault"] = ("开发预览：点击左侧临时按钮进入下一步骤", "Development preview: click the temporary button on the left to enter the next step"),
        ["CaptureWorkspaceStartButtonToFace"] = ("开始按钮：进入面部取景", "Start button: enter face framing"),
        ["CaptureWorkspaceStartButtonToExecution"] = ("开始按钮：进入模块执行", "Start button: enter module execution"),
        ["CaptureWorkspaceStartButtonAvailable"] = ("开始按钮：可用", "Start button: available"),
        ["CaptureWorkspaceStartButtonLocked"] = ("开始按钮：锁定", "Start button: locked"),
        ["CaptureWorkspaceCameraConfirmation"] = ("即将使用摄像头：{0}\n\n请确认用户已在取景范围内，然后开始当前模块。", "Camera to use: {0}\n\nConfirm the user is inside the framing area, then start the current module."),
        ["CaptureWorkspaceCameraUnavailableConfirmation"] = ("当前未检测到可用摄像头，无法开始当前模块。\n\n请连接笔记本摄像头或 USB 摄像头后点击刷新。", "No available camera is detected, so the current module cannot start.\n\nConnect the built-in or USB camera, then click Refresh."),
        ["CaptureWorkspaceDemoInterruptedNotice"] = ("演示播放已中断，请重新播放并完整观看演示视频。", "Demo playback was interrupted. Please replay and watch the full demo video."),
        ["CaptureWorkspaceFaceCheckNotice"] = ("请查看右侧摄像头实时预览，确认用户面部在取景框内；状态正常后点击“开始”。", "Check the live camera preview on the right and confirm the user's face is inside the frame; click Start when the status is normal."),
        ["CaptureWorkspaceSyncTestActionNotice"] = ("请在录制过程中做明显动作并同步发声，例如拍手、点头同时说“现在”。", "During recording, make a clear action while speaking, such as clapping or nodding while saying \"now\"."),
        ["CaptureWorkspaceSyncTestDevNotice"] = ("开发专用：点击中间按钮开始 60 秒音画同步测试。", "Development only: click the central button to start the 60-second A/V sync test."),
        ["CaptureWorkspaceSyncTestDevSwitchNotice"] = ("开发专用：点击中间按钮开始 60 秒音画同步测试；该模块后续可隐藏或删除。", "Development only: click the central button to start the 60-second A/V sync test. This module can be hidden or removed later."),
        ["CaptureWorkspaceDemoStep"] = ("1. 演示视频", "1. Demo"),
        ["CaptureWorkspaceFaceStep"] = ("2. 面部取景", "2. Face framing"),
        ["CaptureWorkspaceCompletedStep"] = ("4. 模块完成", "4. Module completed"),
        ["CaptureWorkspaceFormFillStep"] = ("1. 表单填写", "1. Form filling"),
        ["CaptureWorkspaceFormCompletedStep"] = ("2. 模块完成", "2. Module completed"),
        ["CaptureWorkspacePrepareCheck"] = ("准备检查", "Preparation check"),
        ["CaptureWorkspacePlayDemo"] = ("播放演示", "Play demo"),
        ["CaptureWorkspaceReplayDemo"] = ("重播演示", "Replay demo"),
        ["CaptureWorkspaceStart"] = ("开始", "Start"),
        ["CaptureWorkspaceWatchDone"] = ("已看完", "Watched"),
        ["CaptureWorkspaceEnd"] = ("结束", "End"),
        ["CaptureWorkspaceModuleCompleted"] = ("已完成", "Completed"),
        ["CaptureWorkspaceModuleInProgress"] = ("进行中", "In progress"),
        ["CaptureWorkspaceModulePending"] = ("待完成", "Pending"),
        ["ModuleEyeCalibration"] = ("眼动校准", "Eye calibration"),
        ["ModulePictureBrowse"] = ("图片浏览", "Picture browsing"),
        ["ModuleVideoBrowse"] = ("视频浏览", "Video browsing"),
        ["ModuleVoiceBaseline"] = ("语音基线", "Voice baseline"),
        ["ModuleWordReading"] = ("词语朗读", "Word reading"),
        ["ModuleShortTextReading"] = ("短文朗读", "Passage reading"),
        ["ModuleEmotionQuestion"] = ("情绪问答", "Emotion Q&A"),
        ["ModuleDotProbe"] = ("点探测", "Dot probe"),
        ["ModuleEmotionOddball"] = ("情绪 Oddball", "Emotion Oddball"),
        ["ModuleEmotionLetterSearch"] = ("情绪字母搜索", "Emotion letter search"),
        ["ModuleEmotionStroop"] = ("情绪 Stroop", "Emotion Stroop"),
        ["ModuleBasicInfo"] = ("个人基本信息填写", "Basic information"),
        ["ModuleQuestionnaireA"] = ("A 问卷", "Questionnaire A"),
        ["ModuleQuestionnaireB"] = ("B 问卷", "Questionnaire B"),
        ["ModuleQuestionnaireC"] = ("C 问卷", "Questionnaire C"),
        ["ModuleQuestionnaireD"] = ("D 问卷", "Questionnaire D"),
        ["ModuleQuestionnaireE"] = ("E 问卷", "Questionnaire E"),
        ["ModuleQuestionnaireF"] = ("F 问卷", "Questionnaire F"),
        ["ModuleQuestionnaireG"] = ("G 问卷", "Questionnaire G"),
        ["ModuleQuestionnaireH"] = ("H 问卷", "Questionnaire H"),
        ["ModuleQuestionnaireI"] = ("I 问卷", "Questionnaire I"),
        ["ModuleQuestionnaireJ"] = ("J 问卷", "Questionnaire J"),
        ["ModuleSyncTest"] = ("音画同步测试", "A/V sync test"),
        ["CaptureWorkspaceSyncTestStart"] = ("开始同步测试", "Start sync test"),
        ["CaptureWorkspaceRecordingPending"] = ("录像保存：待开始", "Recording: pending"),
        ["CaptureWorkspaceRecordingActive"] = ("录像保存：录制中", "Recording: active"),
        ["CaptureWorkspaceRecordingFrameCount"] = ("录像保存：录制中 {0} 帧", "Recording: {0} frames"),
        ["CaptureWorkspaceMergingFrameCount"] = ("录像合成中：{0} 帧", "Merging: {0} frames"),
        ["CaptureWorkspaceMergedFrameCount"] = ("音视频保存完成：{0} 帧", "Media saved: {0} frames"),
        ["CaptureWorkspaceMergedWithProbeError"] = ("音视频保存完成：{0} 帧，同步校验失败", "Media saved: {0} frames, sync probe failed"),
        ["CaptureWorkspaceMergeFailed"] = ("音视频合成失败：{0}", "Media merge failed: {0}"),
        ["CaptureWorkspaceRecordingDiscarded"] = ("录像已中断：未保存", "Recording interrupted: not saved"),
        ["CaptureWorkspaceFormPending"] = ("表单保存：待提交", "Form: pending"),
        ["CaptureWorkspaceFormSaving"] = ("表单保存：保存中", "Form: saving"),
        ["CaptureWorkspaceFormSaved"] = ("表单保存：已完成", "Form: saved"),
        ["CaptureWorkspaceFormSaveFailed"] = ("表单保存：失败", "Form: failed"),
        ["CaptureWorkspaceRestTitle"] = ("请休息一下", "Please take a rest"),
        ["CaptureWorkspaceRestRemaining"] = ("剩余 {0} 秒后自动继续。", "Continuing automatically in {0}s."),
        ["CaptureWorkspaceVoiceBaseline"] = ("语音基线", "Voice baseline"),
        ["CaptureWorkspaceVoiceBaselineReady"] = ("准备录制第 {0} / {1} 段", "Ready for segment {0} / {1}"),
        ["CaptureWorkspaceVoiceBaselineKeepSpeaking"] = ("请持续发声，剩余 {0} 秒后自动休息。", "Keep vocalizing. Rest starts in {0}s."),
        ["CaptureWorkspaceVoiceBaselineCompleted"] = ("语音基线完成", "Voice baseline completed"),
        ["CaptureWorkspaceVoiceBaselineStart"] = ("开始语音采集", "Start voice capture"),
        ["CaptureWorkspaceVoiceBaselineStageNotice"] = ("请按中央提示词发声。第一段点击开始后，后续段落将自动流转。", "Please vocalize according to the prompt. After starting the first segment, later segments will continue automatically."),
        ["CaptureWorkspaceVoiceBaselineCompletedNotice"] = ("语音基线采集完成，正在合成音视频。", "Voice baseline completed. Merging media."),
        ["CaptureWorkspaceVoiceBaselineFirstSegmentNotice"] = ("请按中央提示词发声。第一段点击开始后，后续段落将自动流转。", "Please vocalize according to the prompt. After starting the first segment, later segments will continue automatically."),
        ["CaptureWorkspaceWordReading"] = ("词语朗读", "Word reading"),
        ["CaptureWorkspaceWordReadingGroup"] = ("第 {0} / {1} 组", "Group {0} / {1}"),
        ["CaptureWorkspaceWordReadingReady"] = ("准备朗读第 {0} / {1} 组", "Ready for group {0} / {1}"),
        ["CaptureWorkspaceWordReadingRemaining"] = ("请按顺序朗读词语，剩余 {0} 秒后自动休息。", "Read the words in order. Rest starts in {0}s."),
        ["CaptureWorkspaceWordReadingCompletedCount"] = ("已完成 {0} / {1} 组", "Completed {0} / {1} groups"),
        ["CaptureWorkspaceWordReadingCompleted"] = ("词语朗读完成", "Word reading completed"),
        ["CaptureWorkspaceWordReadingStart"] = ("开始词语朗读", "Start word reading"),
        ["CaptureWorkspaceWordReadingStageNotice"] = ("请按中央词组顺序朗读。第一组点击开始后，后续词组将自动流转。", "Read the central word group in order. After starting the first group, later groups will continue automatically."),
        ["CaptureWorkspaceWordReadingCompletedNotice"] = ("词语朗读采集完成，正在合成音视频。", "Word reading completed. Merging media."),
        ["CaptureWorkspaceShortTextReading"] = ("短文朗读", "Passage reading"),
        ["CaptureWorkspaceShortTextReadingPassage"] = ("第 {0} / {1} 段", "Passage {0} / {1}"),
        ["CaptureWorkspaceShortTextReadingReady"] = ("准备朗读第 {0} / {1} 段", "Ready for passage {0} / {1}"),
        ["CaptureWorkspaceShortTextReadingRemaining"] = ("请朗读中央短文，剩余 {0} 秒后自动结束本段。", "Read the passage shown in the center. This passage ends automatically in {0}s."),
        ["CaptureWorkspaceShortTextReadingCompletedCount"] = ("已完成 {0} / {1} 段", "Completed {0} / {1} passages"),
        ["CaptureWorkspaceShortTextReadingCompleted"] = ("短文朗读完成", "Passage reading completed"),
        ["CaptureWorkspaceShortTextReadingStart"] = ("开始短文朗读", "Start passage reading"),
        ["CaptureWorkspaceShortTextReadingStageNotice"] = ("请朗读中央短文。第一段点击开始后，后续段落将按 30 秒朗读和 12 秒休息自动流转。", "Read the passage shown in the center. After starting the first passage, later passages continue automatically with 30 seconds of reading and 12 seconds of rest."),
        ["CaptureWorkspaceShortTextReadingCompletedNotice"] = ("短文朗读采集完成，正在合成音视频。", "Passage reading completed. Merging media."),
        ["CaptureWorkspaceEmotionQuestion"] = ("情绪问答", "Emotion Q&A"),
        ["CaptureWorkspaceEmotionQuestionProgress"] = ("第 {0} / {1} 题", "Question {0} / {1}"),
        ["CaptureWorkspaceEmotionQuestionReady"] = ("准备回答第 {0} / {1} 题", "Ready for question {0} / {1}"),
        ["CaptureWorkspaceEmotionQuestionRemaining"] = ("请回答中央问题，剩余 {0} 秒后自动结束本题。", "Answer the question shown in the center. This question ends automatically in {0}s."),
        ["CaptureWorkspaceEmotionQuestionCompletedCount"] = ("已完成 {0} / {1} 题", "Completed {0} / {1} questions"),
        ["CaptureWorkspaceEmotionQuestionCompleted"] = ("情绪问答完成", "Emotion Q&A completed"),
        ["CaptureWorkspaceEmotionQuestionStart"] = ("开始情绪问答", "Start Emotion Q&A"),
        ["CaptureWorkspaceEmotionQuestionStageNotice"] = ("请根据中央问题进行回答。第一题点击开始后，后续问题将按 30 秒回答和 12 秒休息自动流转。", "Answer the question shown in the center. After starting the first question, later questions continue automatically with 30 seconds of answering and 12 seconds of rest."),
        ["CaptureWorkspaceEmotionQuestionCompletedNotice"] = ("情绪问答采集完成，正在合成音视频。", "Emotion Q&A completed. Merging media."),
        ["CaptureWorkspaceDotProbeUp"] = ("上", "Up"),
        ["CaptureWorkspaceDotProbeDown"] = ("下", "Down"),
        ["CaptureWorkspaceDotProbeRestTitle"] = ("请休息一下", "Please take a short break"),
        ["CaptureWorkspaceDotProbeCompletedNotice"] = ("点探测采集完成，正在合成音视频。", "Dot probe completed. Merging media."),
        ["CaptureWorkspaceBasicInfoTitle"] = ("个人基本信息填写", "Basic information"),
        ["CaptureWorkspaceBasicInfoDescription"] = ("请完成以下必填信息，提交后进入 A 问卷。", "Complete the required fields below, then continue to Questionnaire A."),
        ["CaptureWorkspaceBasicInfoSubmit"] = ("保存并进入 A 问卷", "Save and continue to Questionnaire A"),
        ["CaptureWorkspaceBasicInfoCompleted"] = ("个人基本信息填写完成，准备进入 {0}", "Basic information completed. Ready to enter {0}"),
        ["CaptureWorkspaceBasicInfoGender"] = ("性别", "Gender"),
        ["CaptureWorkspaceBasicInfoBirthDate"] = ("出生日期", "Date of birth"),
        ["CaptureWorkspaceBasicInfoBirthDateHint"] = ("格式：yyyy-MM-dd，例如 1998-06-15", "Format: yyyy-MM-dd, for example 1998-06-15"),
        ["CaptureWorkspaceBasicInfoEducation"] = ("学历", "Education"),
        ["CaptureWorkspaceBasicInfoEducationWithHint"] = ("学历（包括目前在读和肄业、辍学）", "Education, including current study, incomplete study, or dropout"),
        ["CaptureWorkspaceBasicInfoOccupation"] = ("职业", "Occupation"),
        ["CaptureWorkspaceBasicInfoIncomeLevel"] = ("收入水平", "Income level"),
        ["CaptureWorkspaceChooseOption"] = ("请选择", "Select"),
        ["CaptureWorkspaceEditOption"] = ("修改", "Edit"),
        ["CaptureWorkspaceChooseOneOption"] = ("请选择一个答案", "Select one answer"),
        ["CaptureWorkspaceCancel"] = ("取消", "Cancel"),
        ["CaptureWorkspaceBasicInfoRequired"] = ("请先完成以下必填项：{0}", "Please complete required fields: {0}"),
        ["CaptureWorkspaceBasicInfoBirthDateInvalid"] = ("出生日期格式不正确，请按 yyyy-MM-dd 输入，例如 1998-06-15", "Invalid birth date. Please use yyyy-MM-dd, for example 1998-06-15."),
        ["CaptureWorkspaceBasicInfoSaveFailed"] = ("个人基本信息保存失败：{0}", "Failed to save basic information: {0}"),
        ["CaptureWorkspaceBasicInfoStageNotice"] = ("请填写个人基本信息；摄像头预览保留显示，但本模块不进行录像和人脸检测。", "Complete basic information. Camera preview remains visible, but this module does not record video or run face detection."),
        ["CaptureWorkspaceBasicInfoCompletedNotice"] = ("个人基本信息已保存，准备进入 {0}。", "Basic information has been saved. Ready to enter {0}."),
        ["CaptureWorkspaceQuestionnaireATitle"] = ("A 问卷", "Questionnaire A"),
        ["CaptureWorkspaceQuestionnaireASubtitle"] = ("广泛性焦虑量表 GAD-7", "Generalized Anxiety Disorder Scale GAD-7"),
        ["CaptureWorkspaceQuestionnaireAInstruction"] = ("请你仔细阅读下面的句子，根据最近2周的实际情况选择对应的选项。", "Please read each statement carefully and choose the option that best matches your actual situation over the past 2 weeks."),
        ["CaptureWorkspaceQuestionnaireASubmit"] = ("提交并进入 B 问卷", "Submit and continue to Questionnaire B"),
        ["CaptureWorkspaceQuestionnaireACompleted"] = ("A 问卷完成，准备进入 {0}", "Questionnaire A completed. Ready to enter {0}"),
        ["CaptureWorkspaceQuestionnaireBSubtitle"] = ("抑郁量表 PHQ-9", "Patient Health Questionnaire PHQ-9"),
        ["CaptureWorkspaceQuestionnaireCSubtitle"] = ("斯奈思-汉密尔顿快感问卷 SHAPS", "Snaith-Hamilton Pleasure Scale SHAPS"),
        ["CaptureWorkspaceQuestionnaireDSubtitle"] = ("阿森斯失眠量表 AIS", "Athens Insomnia Scale AIS"),
        ["CaptureWorkspaceQuestionnaireESubtitle"] = ("饮食情况问卷", "Dietary questionnaire"),
        ["CaptureWorkspaceQuestionnaireFSubtitle"] = ("压力知觉量表", "Perceived Stress Scale"),
        ["CaptureWorkspaceQuestionnaireGSubtitle"] = ("情绪调节策略量表", "Emotion Regulation Questionnaire"),
        ["CaptureWorkspaceQuestionnaireHSubtitle"] = ("生活事件量表 SLEC", "Life Event Scale SLEC"),
        ["CaptureWorkspaceQuestionnaireISubtitle"] = ("生活环境问卷0-10", "Living Environment Questionnaire 0-10"),
        ["CaptureWorkspaceQuestionnaireJSubtitle"] = ("生活满意度问卷", "Satisfaction With Life Scale"),
        ["CaptureWorkspaceQuestionnaireInstruction"] = ("请你仔细阅读下面的句子，根据最近2周的实际情况选择对应的选项。", "Please read each statement carefully and choose the option that best matches your actual situation over the past 2 weeks."),
        ["CaptureWorkspaceQuestionnaireCInstruction"] = ("请您依据最近一段时间对现实中或者想象中发生的情景所感受到的快乐做出选择，请选择您觉得最贴合的选项。", "Please choose the option that best matches the pleasure you have felt recently in real or imagined situations."),
        ["CaptureWorkspaceQuestionnaireDInstruction"] = ("请仔细阅读下列题项，把意思弄明白，然后根据你最近一个月的实际感觉做出相应的选项。", "Please read each item carefully, make sure you understand it, and choose the option that matches how you have actually felt over the past month."),
        ["CaptureWorkspaceQuestionnaireEInstruction"] = ("请您阅读以下内容，根据自己的实际情况选择合适的选项。", "Please read the following items and choose the option that best matches your actual situation."),
        ["CaptureWorkspaceQuestionnaireFInstruction"] = ("以下问题询问你在过去一个月的一些感受和想法，对于每一个问题，请选出符合你的情况。", "The following questions ask about your feelings and thoughts during the past month. For each question, choose the option that best matches your situation."),
        ["CaptureWorkspaceQuestionnaireGInstruction"] = ("请仔细阅读每一句子，根据您的实际情况选择最符合您的选项。注意：回答这些问题没有对错或好坏之分，请认真作答。", "Please read each sentence carefully and choose the option that best matches your actual situation. There are no right or wrong answers; please answer carefully."),
        ["CaptureWorkspaceQuestionnaireHInstruction"] = ("过去12个月内，你和你的家庭是否发生过下列事件？请仔细阅读下列每一个项目，如果发生过，根据事件给你造成的苦恼程度选择相对应的选项。", "In the past 12 months, have you or your family experienced any of the following events? Please read each item carefully. If it occurred, choose the option matching how much distress it caused you."),
        ["CaptureWorkspaceQuestionnaireIInstruction"] = ("请您阅读以下句子，根据您的实际情况或感受选择最适合您的选项。", "Please read the following statements and choose the option that best matches your actual situation or feelings."),
        ["CaptureWorkspaceQuestionnaireJInstruction"] = ("请您阅读以下句子，根据您的实际感受选择最适合您的选项。", "Please read the following statements and choose the option that best matches how you actually feel."),
        ["CaptureWorkspaceQuestionnaireSubmit"] = ("提交并进入 {0}", "Submit and continue to {0}"),
        ["CaptureWorkspaceQuestionnaireCompleted"] = ("{0} 完成，准备进入 {1}", "{0} completed. Ready to enter {1}"),
        ["CaptureWorkspaceQuestionnaireOptionTitle"] = ("第 {0} 题", "Question {0}"),
        ["CaptureWorkspaceQuestionnaireRequired"] = ("请先完成以下题目：{0}", "Please complete these questions first: {0}"),
        ["CaptureWorkspaceQuestionnaireRequiredLong"] = ("还有 {0} 题未填写，请补充完整后提交。前几题：{1} 等", "There are {0} unanswered questions. Please complete them before submitting. First missing items: {1}, etc."),
        ["CaptureWorkspaceQuestionnaireSaveFailed"] = ("问卷保存失败：{0}", "Failed to save questionnaire: {0}"),
        ["CaptureWorkspaceQuestionnaireCompletedNotice"] = ("{0} 已保存，准备进入 {1}。", "{0} has been saved. Ready to enter {1}.")
    };

    /// <summary>
    /// 当前是否显示中文。true=中文，false=英文。
    /// </summary>
    public bool IsChinese { get; private set; } = true;

    /// <summary>
    /// 语言切换事件。触发后，订阅者（如 LocalizationViewModel）会通知界面刷新。
    /// </summary>
    public event EventHandler? LanguageChanged;

    /// <summary>
    /// 根据 key 获取当前语言的文本。
    /// 如果 key 不存在，直接返回 key 本身，避免崩溃。
    /// </summary>
    public string Text(string key)
    {
        return texts.TryGetValue(key, out var value)
            ? IsChinese ? value.Zh : value.En
            : key;
    }

    /// <summary>
    /// 切换语言并通知所有订阅者。
    /// </summary>
    public void ToggleLanguage()
    {
        IsChinese = !IsChinese;
        LanguageChanged?.Invoke(this, EventArgs.Empty);
    }
}
